### ISSUE TITLE
Multiple Core Generalist displaying

### ISSUE THREAD

**Issue by sharebright** [ACRRM/curriculum-docusaurus#42]
The navigation under All Learning Areas is displaying multiple headings with Core Generalist

![image](https://user-images.githubusercontent.com/1869389/98424145-8e772900-20dc-11eb-981c-2e3c9bb8d1ef.png)

**Comment by sharebright** [comment]
![image](https://user-images.githubusercontent.com/1869389/98424521-a7340e80-20dd-11eb-9227-0751e2fc58dd.png)

**Comment by svict4** [comment]
Yeah it was due to a change yesterday when I was explaining to Craig how it
all works. I will go back in and fix
